-- Создание таблицы для хранения статистики запросов
CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Создание индексов для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_timestamp ON endpoint_hits(hit_timestamp);
CREATE INDEX IF NOT EXISTS idx_uri ON endpoint_hits(uri);
CREATE INDEX IF NOT EXISTS idx_app_uri ON endpoint_hits(app, uri);
CREATE INDEX IF NOT EXISTS idx_ip ON endpoint_hits(ip);

-- Комментарии к таблице и колонкам
COMMENT ON TABLE endpoint_hits IS 'Таблица для хранения статистики запросов к эндпоинтам';
COMMENT ON COLUMN endpoint_hits.id IS 'Уникальный идентификатор записи';
COMMENT ON COLUMN endpoint_hits.app IS 'Название сервиса, отправившего запрос';
COMMENT ON COLUMN endpoint_hits.uri IS 'URI эндпоинта, к которому был запрос';
COMMENT ON COLUMN endpoint_hits.ip IS 'IP-адрес пользователя';
COMMENT ON COLUMN endpoint_hits.hit_timestamp IS 'Время запроса';