version: '3.8'

services:
  statistics-db:
    image: postgres:16-alpine
    container_name: statistics-db
    environment:
      POSTGRES_DB: statistics
      POSTGRES_USER: stat_user
      POSTGRES_PASSWORD: stat_password
    ports:
      - "5432:5432"
    volumes:
      - statistics-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stat_user -d statistics" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - explore-with-me-network
    restart: unless-stopped  # Исправлено с unless-failed на unless-stopped

  statistics-server:
    build:
      context: .
      dockerfile: statistics-server.Dockerfile
    container_name: statistics-server
    ports:
      - "9090:9090"
    depends_on:
      statistics-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://statistics-db:5432/statistics
      SPRING_DATASOURCE_USERNAME: stat_user
      SPRING_DATASOURCE_PASSWORD: stat_password
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - explore-with-me-network
    restart: unless-stopped

networks:
  explore-with-me-network:
    driver: bridge

volumes:
  statistics-db-data: