-- Reactions table
CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    event_id BIGINT NOT NULL REFERENCES events(id),
    reaction_type VARCHAR(10) NOT NULL,
    CONSTRAINT uq_reaction UNIQUE (user_id, event_id)
);
